// src/Home.tsx
export default function Home() {
    return (
        <div className="App-home">
        <h3 style={{color: "white"}}>About Me</h3>
        <div>
        <a
            className="App-link"
            href="https://github.com/peregrinebalas"
            target="_blank"
            rel="noopener noreferrer"
        >
            GitHub
        </a>
        </div>
        <div>
       
        <a
            className="App-link"
            href="https://www.linkedin.com/in/peregrine-balas/"
            target="_blank"
            rel="noopener noreferrer"
        >
            LinkedIn
        </a>
        </div>
        <div>

        <a
            className="App-link"
            href="https://www.instagram.com/peregram_/"
            target="_blank"
            rel="noopener noreferrer"
        >
            Instagram
        </a>
        </div>
        <div>

        <a
            className="App-link"
            href="https://www.facebook.com/peregrine.balas"
            target="_blank"
            rel="noopener noreferrer"
        >
            Facebook
        </a>
        </div>
        </div>
    );
  }

// src/lib/Home.svelte
<script>
  import About from './About.svelte';
  import { title } from './stores.js';
  let links = [
    {
      heading: 'source',
      title: 'GitHub',
      url: 'https://github.com/peregrinebalas',
    },
    {
      heading: 'job',
      title: 'LinkedIn',
      url: 'https://www.linkedin.com/in/peregrine-balas/',
    },
    {
      heading: 'image',
      title: 'Instagram',
      url: 'https://www.instagram.com/peregrinebalas/',
    },
    {
      heading: 'user',
      title: 'Facebook',
      url: 'https://www.facebook.com/peregrine.balas',
    },
  ];
  let currentSection;
  function handleClick(link) {
    $title = link.heading.toUpperCase();
    currentSection = link.title;
  }
</script>

<div class="App-home">
  {#each links as link}
    <label>
      <!-- <button class="section-button" name="sections" value={section.heading}>
        <div class="section-title">{section.title}</div>
      </button> -->
      <a
        class="App-link"
        href={link.url}
        rel="noopener noreferrer"
        on:mouseover={() => handleClick(link)}
        on:mouseleave={() => handleClick({ heading: 'color' })}
      >
        {link.title}
      </a>
    </label>
    <div></div>
  {/each}
</div>
